Add logfmt and tests
forcedotcom/sf-fx-runtime-nodejs pull request #119
Opened 2021-08-27 14:13 UTC by doriskwan

Add logfmt as a formatter and add tests for user-function.logger.ts

Ref: [W-9654765](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000SAhsYAG/view)
Ref: [W-9466762](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000ObzcYAC/view)

2021-08-27 17:08 UTC, joshwlewis requested changes
The rollback of `jsforce` version seems to have changed the error messages related to `data-api.ts`. Is there a way we can do this and continue to use `jsforce@2.0.0` for `data-api.ts`?

2021-08-30 16:34 UTC, joshwlewis approved these changes
Looks great!

2021-08-30 21:04 UTC, schneems requested changes

2021-08-30 21:36 UTC, joshwlewis approved these changes

2021-08-30 21:38 UTC, schneems approved these changes

2021-08-30 21:41 UTC, merged