fix missing/malformed cloud event
forcedotcom/sf-fx-runtime-nodejs pull request #141
Opened 2021-09-07 21:23 UTC by lillianzhang331

When a Function is invoked, the HTTP request headers contain metadata in the Cloud Event format ().
The invokers parse these headers, and use the metadata within to set the various function context objects.
The Functions requests contain a number of custom fields using "extensions" to the Cloud Event base spec.

Currently, the Node.js invoker errors, and returns a slightly unhelpful error message.

For example, if the extensions are missing entirely, the function fails with:
"Could not parse CloudEvent: Cannot read property 'toString' of undefined"

Or if the extensions contain malformed JSON, the function fails with:
"Could not parse CloudEvent: Unexpected end of JSON input"

Fix is to handle these cases and ensure the function can still run, but with empty/null/... salesforce contexts. For malformed JSON, an error will be thrown with "Unexpected end of JSON input" as the error message.

2021-09-07 22:06 UTC, joshwlewis requested changes

2021-09-07 22:06 UTC, joshwlewis commented on src/cloud-event.ts
> +    throw new Error(error.message);
Could we add some helpful context here? I think this is just going to show a `Unexpected end of JSON input` type message which won't give the developer much of a clue to the problem. Maybe something more like ``Could not execute function. Function arguments could not be determined due to invalid JSON body: ${error.message}``.

2021-09-08 13:50 UTC, schneems reviewed
Made a note on the changelog format. Overall change makes sense to me. The tests are mostly kept intact and comments/skip removed. I agree with josh on giving a little love to the error messaging. Thanks for working on this!

2021-09-08 13:50 UTC, schneems commented on CHANGELOG.md
> +- Handle malformed/missing cloud event salesforce extension ([#141](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/141))s
Stray `s` at the end here. 

```suggestion
- Handle malformed/missing cloud event salesforce extension ([#141](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/141))
```

Generally I put new changelog entries at the top so it ends up being in "timeline" order. That way if someone was using main and their stuff broke the first entry on the top is the most likely candidate. I don't think you need to move it, but wanted to leave you a note.

2021-09-08 16:56 UTC, joshwlewis commented on test/cloud-event.ts
> +      expect(error.toString()).to.include("Unexpected end of JSON input");
I think the new error messaging you added is more important to check for. Maybe add an assertion about it?
```suggestion
      expect(error.toString()).to.include("Function arguments could not be determined due to invalid JSON");
      expect(error.toString()).to.include("Unexpected end of JSON input");
```

2021-09-08 19:13 UTC, joshwlewis approved these changes

2021-09-08 19:13 UTC, merged