Rename sffnctx.Apex* to represent Class and Trigger
forcedotcom/sf-fx-runtime-nodejs pull request #152
Opened 2021-09-15 19:59 UTC by cwallsfdc

2021-09-16 15:10 UTC, joshwlewis requested changes
Looks like the tests should be updated too. I see additional usage of `apexClass*` here: https://github.com/forcedotcom/sf-fx-runtime-nodejs/search?q=apexClassId.

Can you also add a note to unreleased section of the changelog explaining the change?

2021-09-16 15:31 UTC, cwallsfdc commented
Looks like I'll need to update `parseCloudEvent`...

```
sfcontext:
        "eyJhcGlWZXJzaW9uIjoiNTAuMCIsI...9fQ==",```

2021-09-17 19:43 UTC, joshwlewis approved these changes

2021-09-17 20:00 UTC, joshwlewis commented
Going to bring this in to main, to prep for a release after the dreamforce deploy moratorium.

2021-09-17 20:00 UTC, merged